CREATE TABLE "skills" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"display_name" text NOT NULL,
	"description" text,
	"category" text DEFAULT 'other',
	"api_base_url" text,
	"auth_type" text DEFAULT 'bearer',
	"docs_url" text,
	"openapi_url" text,
	"npm_package" text,
	"github_repo" text,
	"readme" text,
	"resources" jsonb,
	"version" text DEFAULT '0.1.0',
	"downloads" integer DEFAULT 0,
	"upvotes" integer DEFAULT 0,
	"downvotes" integer DEFAULT 0,
	"verified" boolean DEFAULT false,
	"author_github" text,
	"author_name" text,
	"tags" jsonb DEFAULT '[]'::jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "skills_name_unique" UNIQUE("name")
);
